### PR TITLE
[WIP] Use python code for field map

### PR DESCRIPTION
**Pull request by fkantelberg**
I still have to test it and add some demo code for the calendar but I think this makes the dav.collection much cleaner and shows the concept

### CODE REVIEW

**Comment by hbrunn** [comment]
this looks overly complicated to me, and you don't really clean up code, you just move it. Why not in `dav.collection#to_vobject` after the loop through the mappings:

```python
if self.code_to_vobject:
    tools.safe_eval(
        self.code_to_vobject,
        {
            'record': record,
            'vobj': vobj,
            'self': self,
        },
        ...,
    )
# original code
if 'uid' not in vobj.contents:
    ...
```

`code_to_vobj` then just adds whatever it wants to the vobj based on `record`, for  example using `partner_firstname`'s fields or some localized one's to construct the subfields of the name field. Sorry for adding confusion, I did come back on my original proposal of adding types of mappings in https://github.com/OCA/server-backend/pull/26#issuecomment-531552301, I think the above is much simpler, more powerful and cleaner.

And in `from_vobject` the inverse.

**Comment by fkantelberg** [comment]
Well it's cleaner in the way that the functions for the mapping between vobject/odoo are at the model which is using them.

It's maybe more complex in the source but it allows easier code snippets where you only have to return a value and odoo will take care of the vobject/dict construction which is a good way I think. I just see that I have to drop the required of `field_id` in this case aswell.

Your suggestion is indeed more powerful and cleaner in source but I'm not sure if the code snippets will because you have to construct the vobject.

**Comment by hbrunn** [comment]
the vobject/values dict exists already at that time. To add a complex name, the code would say

```python
vobj.add('n').value = vobject.vcard.Name(
    family=record.lastname or '',
    given=record.firstname or '',
)
```

and to parse it back it would be

```python
if 'n' in vobj.contents:
    n = vobj.n.value
    values['lastname'] = n.family
    values['firstname'] = n.given
```

what's wrong with that?

**Comment by fkantelberg** [comment]
Nothing is wrong with that. My point was just simply if you have more fields that you create with the code snippet you have in that case 2 huge snippets which will do everything. In the current case you have smaller and simpler code snippets. You can use both for the same result but the configuration differs. In both cases we should add a good help.

I'm fine with both and will revert it if you insist.

**Comment by fkantelberg** [comment]
@hbrunn I finally found some time to work further on this.

I was able to test it fully and found out that it wasn't working well with the external creation of events. E.g. thunderbird uses an uuid for the authentication which causes errors when looking up for existing records and will generate the event over and over again. Therefore I added the field_uuid which should point on something like:
```
import uuid
...
uuid = fields.Char(default=lambda self: uuid.uuid4())
```
I don't know how you would handle this. Maybe some `auto_install` modules which will create the uuid field for e.g. `calender.event`.

Additionally using browse is a bad idea because it's not checking if a record actually exists and will crash later when you try reading a field which is why I used a search on the id. I further added the tzinfo fix to the conversion if the result is a datetime object. I also changed the fields of the demo data for better testing.

The change of is_authenticated towards is_authenticated2 is because of deprecation in radicale.

For the next steps I'm planning on working on the right management to have a better control and maybe to move the marked code from radicale.collection to the model `dav.collection`.

**Comment by hbrunn** [comment]
please focus on getting this merged, not on adding more features. Given I won't work on this any time soon, you can better offer your branch for review. I'll close my PR then and link to yours

**Comment by fkantelberg** [comment]
@hbrunn Alright but the "features" are actually customer requirements. Thank you for the work until now.

**Pull request closed without merging**
